apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::343430925817:role/eksctl-rajolinaveen-nodegroup-expe-NodeInstanceRole-vGbcRY9SwiPG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee-role
      userarn: arn:aws:iam::343430925817:user/naveenrajoliuser
      username: naveenrajoliuser

kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-07T23:45:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1376"
  
