# default 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-trainee-role
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["nodes","persistentvolumes"]
  verbs: ["get", "watch", "list"]